deploy:
  image: node:lts-alpine
variables:
  VITE_BASE: "/"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    # Need SSH client for rsync to use - This uses Alpine 'apk' so change if using another container base
    - apk add rsync openssh-client

    # Add the key and known hosts
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/key
    - chmod -R 700 ~/.ssh
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/key

    # Build the website
    - npm install
    - (cd app && npm run predeploy)

    # Sync the built site
    - rsync -cavz --delete ./app/dist/ $REMOTE_SERVER
