server {
  listen 80;
  server_name localhost;
  
  root /usr/share/nginx/html;
  index index.html;
  
  location = /dcr-js {
    return 301 /dcr-js/;
  }

  location /dcr-js/ {
    alias /usr/share/nginx/html/dcr-js/;
    index index.html;
  }
}